apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: myreadinessprobe
spec:
  containers:
  - name: readiness
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 100
    readinessProbe:                                          
      exec:
        command:                                         
        - cat                
        - /tmp/healthy
      initialDelaySeconds: 5          
      periodSeconds: 5                                 
      timeoutSeconds: 30
      failureThreshold: 3
